version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      astro-minor-patch:
        patterns:
          - astro
          - "@astrojs/*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
